name: Initial Algebras Unchained
on:
  push:
    branches: ['master']
jobs:
  check:
    # Using the template from https://github.com/marketplace/actions/setup-agda
    name: Check src/index.agda
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3

      # Setup the latest version of Agda:
      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: '2.6.4'
          agda-stdlib-version: '2.0'
          agda-libraries: |
            https://github.com/agda/agda-categories.git#v0.2.0

      # Check greet.agda, which you can find in tests/agda:
      - run: agda src/index.agda
        working-directory: .
