name: Initial Algebras Unchained
on:
  push:
    branches: ['master']
jobs:
  check:
    name: Check src/index.agda
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3

      # Setup the latest version of Agda:
      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: '2.6.4'
          agda-stdlib-version: '1.7.2'
          agda-libraries: |
            https://github.com/agda/agda-categories#v0.1.7.2

      # Check greet.agda, which you can find in tests/agda:
      - run: agda src/index.agda
        working-directory: .
